import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  const page = [1, 2, 3, 4, 5, 6];
  return (
    <motion.div
      animate={{ opacity: [0, 25, 50, 75, 100] }}
      transition={{ duration: 10 }}
      className="py-[2rem]"
    >
      <Head>
        <title>2022 마을 아카이빙</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.main className="min-h-[100vh] py-5 px-[4rem] flex-1 flex flex-col justify-center items-center">
        <Link href="/" passHref>
          <motion.div className="cursor-pointer select-none">
            <motion.h1 className=" text-center text-[20px] font-semibold">
              2022
            </motion.h1>
            <motion.h1 className=" text-center text-[40px] font-bold text-blue-400">
              마을
            </motion.h1>
            <motion.h1 className=" text-center text-[25px] font-semibold ">
              아카이빙
            </motion.h1>
          </motion.div>
        </Link>

        <motion.p className="text-[16px] text-center mt-5 font-bold">
          제작자 : 여윤하
        </motion.p>

        <motion.div className="mt-6 space-y-2 flex justify-center items-center flex-wrap flex-col">
          {page.map((i) => (
            <motion.a
              animate={{ y: [20, 0] }}
              transition={{ duration: 0.4, type: "spring", stiffness: 500 }}
              key={i}
              className="flex justify-center items-center w-[300px] h-[430px] border-[2.5px] p-1 border-[#eaeaea] border-solid rounded-[10px] duration-100"
            >
              <Image
                alt="달력"
                className="rounded-[10px]"
                width="300px"
                height="430px"
                quality={100}
                priority
                src={`/../public/calendar-yoon/${i}.jpg`.toString()}
              />
            </motion.a>
          ))}
        </motion.div>
      </motion.main>
    </motion.div>
  );
};

export default Home;
