import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  return (
    <motion.div
      animate={{ opacity: [0, 25, 50, 75, 100] }}
      transition={{ duration: 10 }}
      className="py-[2rem]"
    >
      <Head>
        <title>2022 마을 아카이빙</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.main className="min-h-[100vh] py-5 px-[4rem] flex-1 flex flex-col justify-center items-center">
        <Link href="/" passHref>
          <motion.div className="cursor-pointer select-none">
            <motion.h1 className=" text-center text-[30px] font-semibold">
              2022
            </motion.h1>
            <motion.h1 className=" text-center text-[50px] font-bold text-blue-200">
              마을
            </motion.h1>
            <motion.h1 className=" text-center text-[35px] font-semibold ">
              아카이빙
            </motion.h1>
          </motion.div>
        </Link>

        <motion.p className="text-[20px] font-semibold text-center mt-5">
          아래 작품들을 구경해 보세요!
        </motion.p>

        <motion.div className="mt-6 flex justify-center items-center flex-wrap flex-col">
          <Link href="/cats-Spirited-Away">
            <motion.a
              animate={{ y: [20, 0] }}
              transition={{ duration: 0.4, type: "spring", stiffness: 500 }}
              className="flex justify-center items-center w-[300px] h-[200px] mt-2 border-[2.5px] p-1 border-[#eaeaea] hover:border-blue-300 border-solid rounded-[10px] duration-100"
            >
              <Image
                alt="고양이의 행방불명"
                className="rounded-[10px]"
                width="300px"
                height="200px"
                quality={100}
                priority
                src="/public/cat/0.jpg"
              />
            </motion.a>
          </Link>

          <Link href="/was-huajeon">
            <motion.a
              animate={{ y: [20, 0] }}
              transition={{ duration: 0.6, type: "spring", stiffness: 500 }}
              className="flex justify-center items-center w-[300px] h-[430px] mt-2 border-[2.5px] p-1 border-[#eaeaea] hover:border-blue-300 border-solid rounded-[10px] duration-100"
            >
              <Image
                alt="화전 (이였던 것)"
                className="rounded-[10px]"
                width="300px"
                height="430px"
                quality={100}
                priority
                src="/public/was/1.png"
              />
            </motion.a>
          </Link>

          <Link href="/calendar-1">
            <motion.a
              animate={{ y: [20, 0] }}
              transition={{ duration: 0.8, type: "spring", stiffness: 500 }}
              className="flex justify-center items-center w-[300px] h-[430px] mt-2 border-[2.5px] p-1 border-[#eaeaea] hover:border-blue-300 border-solid rounded-[10px] duration-100"
            >
              <Image
                alt="달력 1"
                className="rounded-[10px]"
                width="300px"
                height="430px"
                quality={100}
                priority
                src="/public/calendar-boys/1.png"
              />
            </motion.a>
          </Link>

          <Link href="calendar-2">
            <motion.a
              animate={{ y: [20, 0] }}
              transition={{ duration: 1, type: "spring", stiffness: 500 }}
              className="flex justify-center items-center w-[300px] h-[430px] mt-2 border-[2.5px] p-1 border-[#eaeaea] hover:border-blue-300 border-solid rounded-[10px] duration-100"
            >
              <Image
                alt="달력 2"
                className="rounded-[10px]"
                width="300px"
                height="430px"
                quality={100}
                priority
                src="/public/calendar-son/0.jpg"
              />
            </motion.a>
          </Link>

          <Link href="calendar-3">
            <motion.a
              animate={{ y: [20, 0] }}
              transition={{ duration: 1.2, type: "spring", stiffness: 500 }}
              className="flex justify-center items-center w-[300px] h-[430px] mt-2 border-[2.5px] p-1 border-[#eaeaea] hover:border-blue-300 border-solid rounded-[10px] duration-100"
            >
              <Image
                alt="달력 3"
                className="rounded-[10px]"
                width="300px"
                height="430px"
                quality={100}
                priority
                src="/public/calendar-yoon/12.jpg"
              />
            </motion.a>
          </Link>
        </motion.div>
      </motion.main>
    </motion.div>
  );
};

export default Home;
